### PR TITLE
Add Docker

### PR DESCRIPTION
**Pull request by andrewrynhard**

### CODE REVIEW

**Comment by particledecay** [comment]
Unfortunately, doesn't look like `IfPageNotFound` is going to be good enough for Docker Hub. Maybe using `IfElementOnPage` with `boolean(//h1[contains(@class, "NotFound404")]/text()="404")` as the XPath would work (to grab that comically large "404").

docker_hub

**Comment by andrewrynhard** [comment]
That is ...interesting. I will switch it up to use `IfElementOnPage`.

**Comment by andrewrynhard** [comment]
I got it to work with
```
//h1[contains(@class, 'NotFound404')][text()=404]
```
Saw a panic if I used `boolean()`

**Comment by particledecay** [comment]
I bet it doesn't support that XPath function, good catch

**Review by particledecay — APPROVED** [review]

**Pull request merged**
